use customer_shopping_behaviour;
select * from customer_shopping_behavior;

# What is the total revenu generated by male vs female customer?

select gender, sum(purchase_amount) as revenu
from customer_shopping_behavior
group by gender;

# Which customers used a discount but still spent more than the average purchase amount?
select c.customer_id,c.gender,c.purchase_amount,a.avg_amount
from customer_shopping_behavior c
join
(select avg(purchase_amount)as avg_amount
 from customer_shopping_behavior) as a
where c.discount_applied='Yes' and c.purchase_amount>=a.avg_amount;

# Which are the top 5 products with the highest average review rating?

select * from customer_shopping_behavior;
select c.item_purchased,c.review_rating,a.avg_review_rating
from customer_shopping_behavior c
join
(select avg(review_rating) as avg_review_rating
from customer_shopping_behavior)as a
where c.review_rating>=a.avg_review_rating
order by c.review_rating desc
limit 5;

# compare the average purchase amounts between standarad and express shipping?

select shipping_type, ROUND(avg(purchase_amount),2) as avg_purchase_amount
from customer_shopping_behavior where shipping_type = 'Standard' OR shipping_type ='Express'
group by shipping_type ;

# do subscribed customers spend more? compare average spend and total revenue 
-- between subscribers and non-subscibers?

select distinct(x.total_customers),x.avg_purchase_amount,x.total_revenu 
,x.subscription_status
from customer_shopping_behavior c 
join
(
select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_purchase_amount,
sum(purchase_amount) as total_revenu from customer_shopping_behavior 
 where subscription_status in ('Yes','No')
 group by subscription_status) as x 
 on c.subscription_status = x.subscription_status;
 
 select * from customer_shopping_behavior;
 
 select subscription_status,count(customer_id) as total_numbers,avg(purchase_amount) as avg_amount,
 sum(purchase_amount) as total_revenu
from customer_shopping_behavior
group by subscription_status
order by total_revenu desc;

# which 5 products have the highest percentage of purchases with discounts applied?


SELECT 
    item_purchased,
    ROUND(100 * SUM(case when discount_applied='Yes' then 1 else 0 end) /count(*),2)
    as discount_rate from  customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# segment customers into New,Returning & Loyal based on their total
-- number of previous purchases & show the count of each segment?
 
 with cte as(
 select customer_id,previous_purchases,
 case 
 when previous_purchases=1 then 'New'
 when previous_purchases between 2 and 10 then 'Returning'
 else 'Loyal'
 end as customer_segment
 from customer_shopping_behavior
 )
 select customer_segment,count(*) as total_number_of_customers
 from cte
 group by customer_segment ;
 
 # what are the top 3 most purchased products 
 -- within each category?
 
 with cte as (
 select category,item_purchased,count(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from customer_shopping_behavior
 group by category,item_purchased
 )
 select item_rank,category,item_purchased,total_orders
 from cte
 where item_rank<=3;
 
 # are customers who are repeat buyers (more than
 -- 5 previous purchases) also likely to subscribe?
 
 select subscription_status,count(customer_id) as repeat_buyers
 from customer_shopping_behavior
 where previous_purchases > 5
 group by subscription_status;
 
 # what is the revenue contribution of each age group?
 
 select age_group,sum(purchase_amount) as revenue_contribution
  from customer_shopping_behavior
  group by age_group;